package db.billingdb.model;

import java.util.Date;

public class BaseUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.password
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.deleted
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Short deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.language_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer language_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.status_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer status_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.subscriber_status
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer subscriber_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.last_status_change
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date last_status_change;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.last_login
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date last_login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.user_name
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.failed_attempts
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer failed_attempts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_user.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.id
     *
     * @return the value of base_user.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.id
     *
     * @param id the value for base_user.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.entity_id
     *
     * @return the value of base_user.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.entity_id
     *
     * @param entity_id the value for base_user.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.password
     *
     * @return the value of base_user.password
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.password
     *
     * @param password the value for base_user.password
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.deleted
     *
     * @return the value of base_user.deleted
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Short getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.deleted
     *
     * @param deleted the value for base_user.deleted
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setDeleted(Short deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.language_id
     *
     * @return the value of base_user.language_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getLanguage_id() {
        return language_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.language_id
     *
     * @param language_id the value for base_user.language_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setLanguage_id(Integer language_id) {
        this.language_id = language_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.status_id
     *
     * @return the value of base_user.status_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getStatus_id() {
        return status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.status_id
     *
     * @param status_id the value for base_user.status_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setStatus_id(Integer status_id) {
        this.status_id = status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.subscriber_status
     *
     * @return the value of base_user.subscriber_status
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getSubscriber_status() {
        return subscriber_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.subscriber_status
     *
     * @param subscriber_status the value for base_user.subscriber_status
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setSubscriber_status(Integer subscriber_status) {
        this.subscriber_status = subscriber_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.currency_id
     *
     * @return the value of base_user.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getCurrency_id() {
        return currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.currency_id
     *
     * @param currency_id the value for base_user.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCurrency_id(Integer currency_id) {
        this.currency_id = currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.create_datetime
     *
     * @return the value of base_user.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getCreate_datetime() {
        return create_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.create_datetime
     *
     * @param create_datetime the value for base_user.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCreate_datetime(Date create_datetime) {
        this.create_datetime = create_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.last_status_change
     *
     * @return the value of base_user.last_status_change
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getLast_status_change() {
        return last_status_change;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.last_status_change
     *
     * @param last_status_change the value for base_user.last_status_change
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setLast_status_change(Date last_status_change) {
        this.last_status_change = last_status_change;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.last_login
     *
     * @return the value of base_user.last_login
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getLast_login() {
        return last_login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.last_login
     *
     * @param last_login the value for base_user.last_login
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setLast_login(Date last_login) {
        this.last_login = last_login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.user_name
     *
     * @return the value of base_user.user_name
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.user_name
     *
     * @param user_name the value for base_user.user_name
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.failed_attempts
     *
     * @return the value of base_user.failed_attempts
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getFailed_attempts() {
        return failed_attempts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.failed_attempts
     *
     * @param failed_attempts the value for base_user.failed_attempts
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setFailed_attempts(Integer failed_attempts) {
        this.failed_attempts = failed_attempts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_user.OPTLOCK
     *
     * @return the value of base_user.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_user.OPTLOCK
     *
     * @param OPTLOCK the value for base_user.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}