package db.billingdb.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public BaseUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEntity_idIsNull() {
            addCriterion("entity_id is null");
            return (Criteria) this;
        }

        public Criteria andEntity_idIsNotNull() {
            addCriterion("entity_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntity_idEqualTo(Integer value) {
            addCriterion("entity_id =", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotEqualTo(Integer value) {
            addCriterion("entity_id <>", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idGreaterThan(Integer value) {
            addCriterion("entity_id >", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("entity_id >=", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idLessThan(Integer value) {
            addCriterion("entity_id <", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idLessThanOrEqualTo(Integer value) {
            addCriterion("entity_id <=", value, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idIn(List<Integer> values) {
            addCriterion("entity_id in", values, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotIn(List<Integer> values) {
            addCriterion("entity_id not in", values, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idBetween(Integer value1, Integer value2) {
            addCriterion("entity_id between", value1, value2, "entity_id");
            return (Criteria) this;
        }

        public Criteria andEntity_idNotBetween(Integer value1, Integer value2) {
            addCriterion("entity_id not between", value1, value2, "entity_id");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Short value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Short value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Short value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Short value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Short value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Short value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Short> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Short> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Short value1, Short value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Short value1, Short value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andLanguage_idIsNull() {
            addCriterion("language_id is null");
            return (Criteria) this;
        }

        public Criteria andLanguage_idIsNotNull() {
            addCriterion("language_id is not null");
            return (Criteria) this;
        }

        public Criteria andLanguage_idEqualTo(Integer value) {
            addCriterion("language_id =", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idNotEqualTo(Integer value) {
            addCriterion("language_id <>", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idGreaterThan(Integer value) {
            addCriterion("language_id >", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("language_id >=", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idLessThan(Integer value) {
            addCriterion("language_id <", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idLessThanOrEqualTo(Integer value) {
            addCriterion("language_id <=", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idIn(List<Integer> values) {
            addCriterion("language_id in", values, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idNotIn(List<Integer> values) {
            addCriterion("language_id not in", values, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idBetween(Integer value1, Integer value2) {
            addCriterion("language_id between", value1, value2, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idNotBetween(Integer value1, Integer value2) {
            addCriterion("language_id not between", value1, value2, "language_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idIsNull() {
            addCriterion("status_id is null");
            return (Criteria) this;
        }

        public Criteria andStatus_idIsNotNull() {
            addCriterion("status_id is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_idEqualTo(Integer value) {
            addCriterion("status_id =", value, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idNotEqualTo(Integer value) {
            addCriterion("status_id <>", value, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idGreaterThan(Integer value) {
            addCriterion("status_id >", value, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_id >=", value, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idLessThan(Integer value) {
            addCriterion("status_id <", value, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idLessThanOrEqualTo(Integer value) {
            addCriterion("status_id <=", value, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idIn(List<Integer> values) {
            addCriterion("status_id in", values, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idNotIn(List<Integer> values) {
            addCriterion("status_id not in", values, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idBetween(Integer value1, Integer value2) {
            addCriterion("status_id between", value1, value2, "status_id");
            return (Criteria) this;
        }

        public Criteria andStatus_idNotBetween(Integer value1, Integer value2) {
            addCriterion("status_id not between", value1, value2, "status_id");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusIsNull() {
            addCriterion("subscriber_status is null");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusIsNotNull() {
            addCriterion("subscriber_status is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusEqualTo(Integer value) {
            addCriterion("subscriber_status =", value, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusNotEqualTo(Integer value) {
            addCriterion("subscriber_status <>", value, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusGreaterThan(Integer value) {
            addCriterion("subscriber_status >", value, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("subscriber_status >=", value, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusLessThan(Integer value) {
            addCriterion("subscriber_status <", value, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusLessThanOrEqualTo(Integer value) {
            addCriterion("subscriber_status <=", value, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusIn(List<Integer> values) {
            addCriterion("subscriber_status in", values, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusNotIn(List<Integer> values) {
            addCriterion("subscriber_status not in", values, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusBetween(Integer value1, Integer value2) {
            addCriterion("subscriber_status between", value1, value2, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andSubscriber_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("subscriber_status not between", value1, value2, "subscriber_status");
            return (Criteria) this;
        }

        public Criteria andCurrency_idIsNull() {
            addCriterion("currency_id is null");
            return (Criteria) this;
        }

        public Criteria andCurrency_idIsNotNull() {
            addCriterion("currency_id is not null");
            return (Criteria) this;
        }

        public Criteria andCurrency_idEqualTo(Integer value) {
            addCriterion("currency_id =", value, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idNotEqualTo(Integer value) {
            addCriterion("currency_id <>", value, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idGreaterThan(Integer value) {
            addCriterion("currency_id >", value, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("currency_id >=", value, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idLessThan(Integer value) {
            addCriterion("currency_id <", value, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idLessThanOrEqualTo(Integer value) {
            addCriterion("currency_id <=", value, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idIn(List<Integer> values) {
            addCriterion("currency_id in", values, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idNotIn(List<Integer> values) {
            addCriterion("currency_id not in", values, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idBetween(Integer value1, Integer value2) {
            addCriterion("currency_id between", value1, value2, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCurrency_idNotBetween(Integer value1, Integer value2) {
            addCriterion("currency_id not between", value1, value2, "currency_id");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeIsNull() {
            addCriterion("last_status_change is null");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeIsNotNull() {
            addCriterion("last_status_change is not null");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeEqualTo(Date value) {
            addCriterion("last_status_change =", value, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeNotEqualTo(Date value) {
            addCriterion("last_status_change <>", value, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeGreaterThan(Date value) {
            addCriterion("last_status_change >", value, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_status_change >=", value, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeLessThan(Date value) {
            addCriterion("last_status_change <", value, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeLessThanOrEqualTo(Date value) {
            addCriterion("last_status_change <=", value, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeIn(List<Date> values) {
            addCriterion("last_status_change in", values, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeNotIn(List<Date> values) {
            addCriterion("last_status_change not in", values, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeBetween(Date value1, Date value2) {
            addCriterion("last_status_change between", value1, value2, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_status_changeNotBetween(Date value1, Date value2) {
            addCriterion("last_status_change not between", value1, value2, "last_status_change");
            return (Criteria) this;
        }

        public Criteria andLast_loginIsNull() {
            addCriterion("last_login is null");
            return (Criteria) this;
        }

        public Criteria andLast_loginIsNotNull() {
            addCriterion("last_login is not null");
            return (Criteria) this;
        }

        public Criteria andLast_loginEqualTo(Date value) {
            addCriterion("last_login =", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginNotEqualTo(Date value) {
            addCriterion("last_login <>", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginGreaterThan(Date value) {
            addCriterion("last_login >", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login >=", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginLessThan(Date value) {
            addCriterion("last_login <", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginLessThanOrEqualTo(Date value) {
            addCriterion("last_login <=", value, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginIn(List<Date> values) {
            addCriterion("last_login in", values, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginNotIn(List<Date> values) {
            addCriterion("last_login not in", values, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginBetween(Date value1, Date value2) {
            addCriterion("last_login between", value1, value2, "last_login");
            return (Criteria) this;
        }

        public Criteria andLast_loginNotBetween(Date value1, Date value2) {
            addCriterion("last_login not between", value1, value2, "last_login");
            return (Criteria) this;
        }

        public Criteria andUser_nameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUser_nameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUser_nameEqualTo(String value) {
            addCriterion("user_name =", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameGreaterThan(String value) {
            addCriterion("user_name >", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLessThan(String value) {
            addCriterion("user_name <", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLike(String value) {
            addCriterion("user_name like", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotLike(String value) {
            addCriterion("user_name not like", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameIn(List<String> values) {
            addCriterion("user_name in", values, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "user_name");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsIsNull() {
            addCriterion("failed_attempts is null");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsIsNotNull() {
            addCriterion("failed_attempts is not null");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsEqualTo(Integer value) {
            addCriterion("failed_attempts =", value, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsNotEqualTo(Integer value) {
            addCriterion("failed_attempts <>", value, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsGreaterThan(Integer value) {
            addCriterion("failed_attempts >", value, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsGreaterThanOrEqualTo(Integer value) {
            addCriterion("failed_attempts >=", value, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsLessThan(Integer value) {
            addCriterion("failed_attempts <", value, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsLessThanOrEqualTo(Integer value) {
            addCriterion("failed_attempts <=", value, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsIn(List<Integer> values) {
            addCriterion("failed_attempts in", values, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsNotIn(List<Integer> values) {
            addCriterion("failed_attempts not in", values, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsBetween(Integer value1, Integer value2) {
            addCriterion("failed_attempts between", value1, value2, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andFailed_attemptsNotBetween(Integer value1, Integer value2) {
            addCriterion("failed_attempts not between", value1, value2, "failed_attempts");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIsNull() {
            addCriterion("OPTLOCK is null");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIsNotNull() {
            addCriterion("OPTLOCK is not null");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKEqualTo(Integer value) {
            addCriterion("OPTLOCK =", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotEqualTo(Integer value) {
            addCriterion("OPTLOCK <>", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKGreaterThan(Integer value) {
            addCriterion("OPTLOCK >", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPTLOCK >=", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKLessThan(Integer value) {
            addCriterion("OPTLOCK <", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKLessThanOrEqualTo(Integer value) {
            addCriterion("OPTLOCK <=", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIn(List<Integer> values) {
            addCriterion("OPTLOCK in", values, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotIn(List<Integer> values) {
            addCriterion("OPTLOCK not in", values, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKBetween(Integer value1, Integer value2) {
            addCriterion("OPTLOCK between", value1, value2, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotBetween(Integer value1, Integer value2) {
            addCriterion("OPTLOCK not between", value1, value2, "OPTLOCK");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_user
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 21:28:38 IST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}