package db.billingdb.model;

import java.util.Date;

public class Blacklist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.source
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.credit_card
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer credit_card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.credit_card_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer credit_card_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.contact_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer contact_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.user_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.id
     *
     * @return the value of blacklist.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.id
     *
     * @param id the value for blacklist.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.entity_id
     *
     * @return the value of blacklist.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.entity_id
     *
     * @param entity_id the value for blacklist.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.create_datetime
     *
     * @return the value of blacklist.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getCreate_datetime() {
        return create_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.create_datetime
     *
     * @param create_datetime the value for blacklist.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCreate_datetime(Date create_datetime) {
        this.create_datetime = create_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.type
     *
     * @return the value of blacklist.type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.type
     *
     * @param type the value for blacklist.type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.source
     *
     * @return the value of blacklist.source
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.source
     *
     * @param source the value for blacklist.source
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.credit_card
     *
     * @return the value of blacklist.credit_card
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getCredit_card() {
        return credit_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.credit_card
     *
     * @param credit_card the value for blacklist.credit_card
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCredit_card(Integer credit_card) {
        this.credit_card = credit_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.credit_card_id
     *
     * @return the value of blacklist.credit_card_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getCredit_card_id() {
        return credit_card_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.credit_card_id
     *
     * @param credit_card_id the value for blacklist.credit_card_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCredit_card_id(Integer credit_card_id) {
        this.credit_card_id = credit_card_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.contact_id
     *
     * @return the value of blacklist.contact_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getContact_id() {
        return contact_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.contact_id
     *
     * @param contact_id the value for blacklist.contact_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setContact_id(Integer contact_id) {
        this.contact_id = contact_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.user_id
     *
     * @return the value of blacklist.user_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.user_id
     *
     * @param user_id the value for blacklist.user_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.OPTLOCK
     *
     * @return the value of blacklist.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.OPTLOCK
     *
     * @param OPTLOCK the value for blacklist.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}