package db.billingdb.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContactExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public ContactExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameIsNull() {
            addCriterion("organization_name is null");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameIsNotNull() {
            addCriterion("organization_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameEqualTo(String value) {
            addCriterion("organization_name =", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotEqualTo(String value) {
            addCriterion("organization_name <>", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameGreaterThan(String value) {
            addCriterion("organization_name >", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameGreaterThanOrEqualTo(String value) {
            addCriterion("organization_name >=", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameLessThan(String value) {
            addCriterion("organization_name <", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameLessThanOrEqualTo(String value) {
            addCriterion("organization_name <=", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameLike(String value) {
            addCriterion("organization_name like", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotLike(String value) {
            addCriterion("organization_name not like", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameIn(List<String> values) {
            addCriterion("organization_name in", values, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotIn(List<String> values) {
            addCriterion("organization_name not in", values, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameBetween(String value1, String value2) {
            addCriterion("organization_name between", value1, value2, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotBetween(String value1, String value2) {
            addCriterion("organization_name not between", value1, value2, "organization_name");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1IsNull() {
            addCriterion("street_addres1 is null");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1IsNotNull() {
            addCriterion("street_addres1 is not null");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1EqualTo(String value) {
            addCriterion("street_addres1 =", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1NotEqualTo(String value) {
            addCriterion("street_addres1 <>", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1GreaterThan(String value) {
            addCriterion("street_addres1 >", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1GreaterThanOrEqualTo(String value) {
            addCriterion("street_addres1 >=", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1LessThan(String value) {
            addCriterion("street_addres1 <", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1LessThanOrEqualTo(String value) {
            addCriterion("street_addres1 <=", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1Like(String value) {
            addCriterion("street_addres1 like", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1NotLike(String value) {
            addCriterion("street_addres1 not like", value, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1In(List<String> values) {
            addCriterion("street_addres1 in", values, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1NotIn(List<String> values) {
            addCriterion("street_addres1 not in", values, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1Between(String value1, String value2) {
            addCriterion("street_addres1 between", value1, value2, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres1NotBetween(String value1, String value2) {
            addCriterion("street_addres1 not between", value1, value2, "street_addres1");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2IsNull() {
            addCriterion("street_addres2 is null");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2IsNotNull() {
            addCriterion("street_addres2 is not null");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2EqualTo(String value) {
            addCriterion("street_addres2 =", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2NotEqualTo(String value) {
            addCriterion("street_addres2 <>", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2GreaterThan(String value) {
            addCriterion("street_addres2 >", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2GreaterThanOrEqualTo(String value) {
            addCriterion("street_addres2 >=", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2LessThan(String value) {
            addCriterion("street_addres2 <", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2LessThanOrEqualTo(String value) {
            addCriterion("street_addres2 <=", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2Like(String value) {
            addCriterion("street_addres2 like", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2NotLike(String value) {
            addCriterion("street_addres2 not like", value, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2In(List<String> values) {
            addCriterion("street_addres2 in", values, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2NotIn(List<String> values) {
            addCriterion("street_addres2 not in", values, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2Between(String value1, String value2) {
            addCriterion("street_addres2 between", value1, value2, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andStreet_addres2NotBetween(String value1, String value2) {
            addCriterion("street_addres2 not between", value1, value2, "street_addres2");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andState_provinceIsNull() {
            addCriterion("state_province is null");
            return (Criteria) this;
        }

        public Criteria andState_provinceIsNotNull() {
            addCriterion("state_province is not null");
            return (Criteria) this;
        }

        public Criteria andState_provinceEqualTo(String value) {
            addCriterion("state_province =", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceNotEqualTo(String value) {
            addCriterion("state_province <>", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceGreaterThan(String value) {
            addCriterion("state_province >", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceGreaterThanOrEqualTo(String value) {
            addCriterion("state_province >=", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceLessThan(String value) {
            addCriterion("state_province <", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceLessThanOrEqualTo(String value) {
            addCriterion("state_province <=", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceLike(String value) {
            addCriterion("state_province like", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceNotLike(String value) {
            addCriterion("state_province not like", value, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceIn(List<String> values) {
            addCriterion("state_province in", values, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceNotIn(List<String> values) {
            addCriterion("state_province not in", values, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceBetween(String value1, String value2) {
            addCriterion("state_province between", value1, value2, "state_province");
            return (Criteria) this;
        }

        public Criteria andState_provinceNotBetween(String value1, String value2) {
            addCriterion("state_province not between", value1, value2, "state_province");
            return (Criteria) this;
        }

        public Criteria andPostal_codeIsNull() {
            addCriterion("postal_code is null");
            return (Criteria) this;
        }

        public Criteria andPostal_codeIsNotNull() {
            addCriterion("postal_code is not null");
            return (Criteria) this;
        }

        public Criteria andPostal_codeEqualTo(String value) {
            addCriterion("postal_code =", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeNotEqualTo(String value) {
            addCriterion("postal_code <>", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeGreaterThan(String value) {
            addCriterion("postal_code >", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeGreaterThanOrEqualTo(String value) {
            addCriterion("postal_code >=", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeLessThan(String value) {
            addCriterion("postal_code <", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeLessThanOrEqualTo(String value) {
            addCriterion("postal_code <=", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeLike(String value) {
            addCriterion("postal_code like", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeNotLike(String value) {
            addCriterion("postal_code not like", value, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeIn(List<String> values) {
            addCriterion("postal_code in", values, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeNotIn(List<String> values) {
            addCriterion("postal_code not in", values, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeBetween(String value1, String value2) {
            addCriterion("postal_code between", value1, value2, "postal_code");
            return (Criteria) this;
        }

        public Criteria andPostal_codeNotBetween(String value1, String value2) {
            addCriterion("postal_code not between", value1, value2, "postal_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeIsNull() {
            addCriterion("country_code is null");
            return (Criteria) this;
        }

        public Criteria andCountry_codeIsNotNull() {
            addCriterion("country_code is not null");
            return (Criteria) this;
        }

        public Criteria andCountry_codeEqualTo(String value) {
            addCriterion("country_code =", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotEqualTo(String value) {
            addCriterion("country_code <>", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeGreaterThan(String value) {
            addCriterion("country_code >", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeGreaterThanOrEqualTo(String value) {
            addCriterion("country_code >=", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeLessThan(String value) {
            addCriterion("country_code <", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeLessThanOrEqualTo(String value) {
            addCriterion("country_code <=", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeLike(String value) {
            addCriterion("country_code like", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotLike(String value) {
            addCriterion("country_code not like", value, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeIn(List<String> values) {
            addCriterion("country_code in", values, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotIn(List<String> values) {
            addCriterion("country_code not in", values, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeBetween(String value1, String value2) {
            addCriterion("country_code between", value1, value2, "country_code");
            return (Criteria) this;
        }

        public Criteria andCountry_codeNotBetween(String value1, String value2) {
            addCriterion("country_code not between", value1, value2, "country_code");
            return (Criteria) this;
        }

        public Criteria andLast_nameIsNull() {
            addCriterion("last_name is null");
            return (Criteria) this;
        }

        public Criteria andLast_nameIsNotNull() {
            addCriterion("last_name is not null");
            return (Criteria) this;
        }

        public Criteria andLast_nameEqualTo(String value) {
            addCriterion("last_name =", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameNotEqualTo(String value) {
            addCriterion("last_name <>", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameGreaterThan(String value) {
            addCriterion("last_name >", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameGreaterThanOrEqualTo(String value) {
            addCriterion("last_name >=", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameLessThan(String value) {
            addCriterion("last_name <", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameLessThanOrEqualTo(String value) {
            addCriterion("last_name <=", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameLike(String value) {
            addCriterion("last_name like", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameNotLike(String value) {
            addCriterion("last_name not like", value, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameIn(List<String> values) {
            addCriterion("last_name in", values, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameNotIn(List<String> values) {
            addCriterion("last_name not in", values, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameBetween(String value1, String value2) {
            addCriterion("last_name between", value1, value2, "last_name");
            return (Criteria) this;
        }

        public Criteria andLast_nameNotBetween(String value1, String value2) {
            addCriterion("last_name not between", value1, value2, "last_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameIsNull() {
            addCriterion("first_name is null");
            return (Criteria) this;
        }

        public Criteria andFirst_nameIsNotNull() {
            addCriterion("first_name is not null");
            return (Criteria) this;
        }

        public Criteria andFirst_nameEqualTo(String value) {
            addCriterion("first_name =", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameNotEqualTo(String value) {
            addCriterion("first_name <>", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameGreaterThan(String value) {
            addCriterion("first_name >", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameGreaterThanOrEqualTo(String value) {
            addCriterion("first_name >=", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameLessThan(String value) {
            addCriterion("first_name <", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameLessThanOrEqualTo(String value) {
            addCriterion("first_name <=", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameLike(String value) {
            addCriterion("first_name like", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameNotLike(String value) {
            addCriterion("first_name not like", value, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameIn(List<String> values) {
            addCriterion("first_name in", values, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameNotIn(List<String> values) {
            addCriterion("first_name not in", values, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameBetween(String value1, String value2) {
            addCriterion("first_name between", value1, value2, "first_name");
            return (Criteria) this;
        }

        public Criteria andFirst_nameNotBetween(String value1, String value2) {
            addCriterion("first_name not between", value1, value2, "first_name");
            return (Criteria) this;
        }

        public Criteria andPerson_initialIsNull() {
            addCriterion("person_initial is null");
            return (Criteria) this;
        }

        public Criteria andPerson_initialIsNotNull() {
            addCriterion("person_initial is not null");
            return (Criteria) this;
        }

        public Criteria andPerson_initialEqualTo(String value) {
            addCriterion("person_initial =", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialNotEqualTo(String value) {
            addCriterion("person_initial <>", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialGreaterThan(String value) {
            addCriterion("person_initial >", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialGreaterThanOrEqualTo(String value) {
            addCriterion("person_initial >=", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialLessThan(String value) {
            addCriterion("person_initial <", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialLessThanOrEqualTo(String value) {
            addCriterion("person_initial <=", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialLike(String value) {
            addCriterion("person_initial like", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialNotLike(String value) {
            addCriterion("person_initial not like", value, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialIn(List<String> values) {
            addCriterion("person_initial in", values, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialNotIn(List<String> values) {
            addCriterion("person_initial not in", values, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialBetween(String value1, String value2) {
            addCriterion("person_initial between", value1, value2, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_initialNotBetween(String value1, String value2) {
            addCriterion("person_initial not between", value1, value2, "person_initial");
            return (Criteria) this;
        }

        public Criteria andPerson_titleIsNull() {
            addCriterion("person_title is null");
            return (Criteria) this;
        }

        public Criteria andPerson_titleIsNotNull() {
            addCriterion("person_title is not null");
            return (Criteria) this;
        }

        public Criteria andPerson_titleEqualTo(String value) {
            addCriterion("person_title =", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleNotEqualTo(String value) {
            addCriterion("person_title <>", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleGreaterThan(String value) {
            addCriterion("person_title >", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleGreaterThanOrEqualTo(String value) {
            addCriterion("person_title >=", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleLessThan(String value) {
            addCriterion("person_title <", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleLessThanOrEqualTo(String value) {
            addCriterion("person_title <=", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleLike(String value) {
            addCriterion("person_title like", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleNotLike(String value) {
            addCriterion("person_title not like", value, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleIn(List<String> values) {
            addCriterion("person_title in", values, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleNotIn(List<String> values) {
            addCriterion("person_title not in", values, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleBetween(String value1, String value2) {
            addCriterion("person_title between", value1, value2, "person_title");
            return (Criteria) this;
        }

        public Criteria andPerson_titleNotBetween(String value1, String value2) {
            addCriterion("person_title not between", value1, value2, "person_title");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeIsNull() {
            addCriterion("phone_country_code is null");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeIsNotNull() {
            addCriterion("phone_country_code is not null");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeEqualTo(Integer value) {
            addCriterion("phone_country_code =", value, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeNotEqualTo(Integer value) {
            addCriterion("phone_country_code <>", value, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeGreaterThan(Integer value) {
            addCriterion("phone_country_code >", value, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeGreaterThanOrEqualTo(Integer value) {
            addCriterion("phone_country_code >=", value, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeLessThan(Integer value) {
            addCriterion("phone_country_code <", value, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeLessThanOrEqualTo(Integer value) {
            addCriterion("phone_country_code <=", value, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeIn(List<Integer> values) {
            addCriterion("phone_country_code in", values, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeNotIn(List<Integer> values) {
            addCriterion("phone_country_code not in", values, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeBetween(Integer value1, Integer value2) {
            addCriterion("phone_country_code between", value1, value2, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_country_codeNotBetween(Integer value1, Integer value2) {
            addCriterion("phone_country_code not between", value1, value2, "phone_country_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeIsNull() {
            addCriterion("phone_area_code is null");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeIsNotNull() {
            addCriterion("phone_area_code is not null");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeEqualTo(Integer value) {
            addCriterion("phone_area_code =", value, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeNotEqualTo(Integer value) {
            addCriterion("phone_area_code <>", value, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeGreaterThan(Integer value) {
            addCriterion("phone_area_code >", value, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeGreaterThanOrEqualTo(Integer value) {
            addCriterion("phone_area_code >=", value, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeLessThan(Integer value) {
            addCriterion("phone_area_code <", value, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeLessThanOrEqualTo(Integer value) {
            addCriterion("phone_area_code <=", value, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeIn(List<Integer> values) {
            addCriterion("phone_area_code in", values, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeNotIn(List<Integer> values) {
            addCriterion("phone_area_code not in", values, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeBetween(Integer value1, Integer value2) {
            addCriterion("phone_area_code between", value1, value2, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_area_codeNotBetween(Integer value1, Integer value2) {
            addCriterion("phone_area_code not between", value1, value2, "phone_area_code");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberIsNull() {
            addCriterion("phone_phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberIsNotNull() {
            addCriterion("phone_phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberEqualTo(String value) {
            addCriterion("phone_phone_number =", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberNotEqualTo(String value) {
            addCriterion("phone_phone_number <>", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberGreaterThan(String value) {
            addCriterion("phone_phone_number >", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_phone_number >=", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberLessThan(String value) {
            addCriterion("phone_phone_number <", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberLessThanOrEqualTo(String value) {
            addCriterion("phone_phone_number <=", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberLike(String value) {
            addCriterion("phone_phone_number like", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberNotLike(String value) {
            addCriterion("phone_phone_number not like", value, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberIn(List<String> values) {
            addCriterion("phone_phone_number in", values, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberNotIn(List<String> values) {
            addCriterion("phone_phone_number not in", values, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberBetween(String value1, String value2) {
            addCriterion("phone_phone_number between", value1, value2, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andPhone_phone_numberNotBetween(String value1, String value2) {
            addCriterion("phone_phone_number not between", value1, value2, "phone_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeIsNull() {
            addCriterion("fax_country_code is null");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeIsNotNull() {
            addCriterion("fax_country_code is not null");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeEqualTo(Integer value) {
            addCriterion("fax_country_code =", value, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeNotEqualTo(Integer value) {
            addCriterion("fax_country_code <>", value, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeGreaterThan(Integer value) {
            addCriterion("fax_country_code >", value, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fax_country_code >=", value, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeLessThan(Integer value) {
            addCriterion("fax_country_code <", value, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeLessThanOrEqualTo(Integer value) {
            addCriterion("fax_country_code <=", value, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeIn(List<Integer> values) {
            addCriterion("fax_country_code in", values, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeNotIn(List<Integer> values) {
            addCriterion("fax_country_code not in", values, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeBetween(Integer value1, Integer value2) {
            addCriterion("fax_country_code between", value1, value2, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_country_codeNotBetween(Integer value1, Integer value2) {
            addCriterion("fax_country_code not between", value1, value2, "fax_country_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeIsNull() {
            addCriterion("fax_area_code is null");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeIsNotNull() {
            addCriterion("fax_area_code is not null");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeEqualTo(Integer value) {
            addCriterion("fax_area_code =", value, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeNotEqualTo(Integer value) {
            addCriterion("fax_area_code <>", value, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeGreaterThan(Integer value) {
            addCriterion("fax_area_code >", value, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fax_area_code >=", value, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeLessThan(Integer value) {
            addCriterion("fax_area_code <", value, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeLessThanOrEqualTo(Integer value) {
            addCriterion("fax_area_code <=", value, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeIn(List<Integer> values) {
            addCriterion("fax_area_code in", values, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeNotIn(List<Integer> values) {
            addCriterion("fax_area_code not in", values, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeBetween(Integer value1, Integer value2) {
            addCriterion("fax_area_code between", value1, value2, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_area_codeNotBetween(Integer value1, Integer value2) {
            addCriterion("fax_area_code not between", value1, value2, "fax_area_code");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberIsNull() {
            addCriterion("fax_phone_number is null");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberIsNotNull() {
            addCriterion("fax_phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberEqualTo(String value) {
            addCriterion("fax_phone_number =", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberNotEqualTo(String value) {
            addCriterion("fax_phone_number <>", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberGreaterThan(String value) {
            addCriterion("fax_phone_number >", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberGreaterThanOrEqualTo(String value) {
            addCriterion("fax_phone_number >=", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberLessThan(String value) {
            addCriterion("fax_phone_number <", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberLessThanOrEqualTo(String value) {
            addCriterion("fax_phone_number <=", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberLike(String value) {
            addCriterion("fax_phone_number like", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberNotLike(String value) {
            addCriterion("fax_phone_number not like", value, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberIn(List<String> values) {
            addCriterion("fax_phone_number in", values, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberNotIn(List<String> values) {
            addCriterion("fax_phone_number not in", values, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberBetween(String value1, String value2) {
            addCriterion("fax_phone_number between", value1, value2, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andFax_phone_numberNotBetween(String value1, String value2) {
            addCriterion("fax_phone_number not between", value1, value2, "fax_phone_number");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Short value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Short value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Short value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Short value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Short value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Short value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Short> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Short> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Short value1, Short value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Short value1, Short value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andNotification_includeIsNull() {
            addCriterion("notification_include is null");
            return (Criteria) this;
        }

        public Criteria andNotification_includeIsNotNull() {
            addCriterion("notification_include is not null");
            return (Criteria) this;
        }

        public Criteria andNotification_includeEqualTo(Short value) {
            addCriterion("notification_include =", value, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeNotEqualTo(Short value) {
            addCriterion("notification_include <>", value, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeGreaterThan(Short value) {
            addCriterion("notification_include >", value, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeGreaterThanOrEqualTo(Short value) {
            addCriterion("notification_include >=", value, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeLessThan(Short value) {
            addCriterion("notification_include <", value, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeLessThanOrEqualTo(Short value) {
            addCriterion("notification_include <=", value, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeIn(List<Short> values) {
            addCriterion("notification_include in", values, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeNotIn(List<Short> values) {
            addCriterion("notification_include not in", values, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeBetween(Short value1, Short value2) {
            addCriterion("notification_include between", value1, value2, "notification_include");
            return (Criteria) this;
        }

        public Criteria andNotification_includeNotBetween(Short value1, Short value2) {
            addCriterion("notification_include not between", value1, value2, "notification_include");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Integer value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Integer value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Integer value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Integer> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIsNull() {
            addCriterion("OPTLOCK is null");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIsNotNull() {
            addCriterion("OPTLOCK is not null");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKEqualTo(Integer value) {
            addCriterion("OPTLOCK =", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotEqualTo(Integer value) {
            addCriterion("OPTLOCK <>", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKGreaterThan(Integer value) {
            addCriterion("OPTLOCK >", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPTLOCK >=", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKLessThan(Integer value) {
            addCriterion("OPTLOCK <", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKLessThanOrEqualTo(Integer value) {
            addCriterion("OPTLOCK <=", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIn(List<Integer> values) {
            addCriterion("OPTLOCK in", values, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotIn(List<Integer> values) {
            addCriterion("OPTLOCK not in", values, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKBetween(Integer value1, Integer value2) {
            addCriterion("OPTLOCK between", value1, value2, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotBetween(Integer value1, Integer value2) {
            addCriterion("OPTLOCK not between", value1, value2, "OPTLOCK");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 21:28:38 IST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}