package db.billingdb.model;

public class ContactType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_type.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_type.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_type.is_primary
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Short is_primary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_type.id
     *
     * @return the value of contact_type.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_type.id
     *
     * @param id the value for contact_type.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_type.entity_id
     *
     * @return the value of contact_type.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_type.entity_id
     *
     * @param entity_id the value for contact_type.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_type.is_primary
     *
     * @return the value of contact_type.is_primary
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Short getIs_primary() {
        return is_primary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_type.is_primary
     *
     * @param is_primary the value for contact_type.is_primary
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setIs_primary(Short is_primary) {
        this.is_primary = is_primary;
    }
}