package db.billingdb.model;

public class ContactMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_map.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_map.contact_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer contact_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_map.type_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_map.table_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer table_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_map.foreign_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer foreign_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact_map.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_map.id
     *
     * @return the value of contact_map.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_map.id
     *
     * @param id the value for contact_map.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_map.contact_id
     *
     * @return the value of contact_map.contact_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getContact_id() {
        return contact_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_map.contact_id
     *
     * @param contact_id the value for contact_map.contact_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setContact_id(Integer contact_id) {
        this.contact_id = contact_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_map.type_id
     *
     * @return the value of contact_map.type_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_map.type_id
     *
     * @param type_id the value for contact_map.type_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_map.table_id
     *
     * @return the value of contact_map.table_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getTable_id() {
        return table_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_map.table_id
     *
     * @param table_id the value for contact_map.table_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setTable_id(Integer table_id) {
        this.table_id = table_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_map.foreign_id
     *
     * @return the value of contact_map.foreign_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getForeign_id() {
        return foreign_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_map.foreign_id
     *
     * @param foreign_id the value for contact_map.foreign_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setForeign_id(Integer foreign_id) {
        this.foreign_id = foreign_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact_map.OPTLOCK
     *
     * @return the value of contact_map.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact_map.OPTLOCK
     *
     * @param OPTLOCK the value for contact_map.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}