package db.billingdb.model;

import java.util.Date;

public class CurrencyExchange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_exchange.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_exchange.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_exchange.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_exchange.rate
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_exchange.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date create_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_exchange.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_exchange.id
     *
     * @return the value of currency_exchange.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_exchange.id
     *
     * @param id the value for currency_exchange.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_exchange.entity_id
     *
     * @return the value of currency_exchange.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_exchange.entity_id
     *
     * @param entity_id the value for currency_exchange.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_exchange.currency_id
     *
     * @return the value of currency_exchange.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getCurrency_id() {
        return currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_exchange.currency_id
     *
     * @param currency_id the value for currency_exchange.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCurrency_id(Integer currency_id) {
        this.currency_id = currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_exchange.rate
     *
     * @return the value of currency_exchange.rate
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_exchange.rate
     *
     * @param rate the value for currency_exchange.rate
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_exchange.create_datetime
     *
     * @return the value of currency_exchange.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getCreate_datetime() {
        return create_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_exchange.create_datetime
     *
     * @param create_datetime the value for currency_exchange.create_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCreate_datetime(Date create_datetime) {
        this.create_datetime = create_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_exchange.OPTLOCK
     *
     * @return the value of currency_exchange.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_exchange.OPTLOCK
     *
     * @param OPTLOCK the value for currency_exchange.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}