package db.billingdb.model;

public class EntityPaymentMethodMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_payment_method_map.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_payment_method_map.payment_method_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer payment_method_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_payment_method_map.entity_id
     *
     * @return the value of entity_payment_method_map.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_payment_method_map.entity_id
     *
     * @param entity_id the value for entity_payment_method_map.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_payment_method_map.payment_method_id
     *
     * @return the value of entity_payment_method_map.payment_method_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getPayment_method_id() {
        return payment_method_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_payment_method_map.payment_method_id
     *
     * @param payment_method_id the value for entity_payment_method_map.payment_method_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setPayment_method_id(Integer payment_method_id) {
        this.payment_method_id = payment_method_id;
    }
}