package db.billingdb.model;

public class EventLogModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_log_module.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_log_module.id
     *
     * @return the value of event_log_module.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_log_module.id
     *
     * @param id the value for event_log_module.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }
}