package db.billingdb.model;

import java.util.Date;

public class ListFieldEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.list_field_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer list_field_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.list_entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer list_entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.min_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer min_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.max_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer max_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.min_str_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private String min_str_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.max_str_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private String max_str_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.min_date_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date min_date_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.max_date_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date max_date_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_field_entity.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.id
     *
     * @return the value of list_field_entity.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.id
     *
     * @param id the value for list_field_entity.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.list_field_id
     *
     * @return the value of list_field_entity.list_field_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getList_field_id() {
        return list_field_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.list_field_id
     *
     * @param list_field_id the value for list_field_entity.list_field_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setList_field_id(Integer list_field_id) {
        this.list_field_id = list_field_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.list_entity_id
     *
     * @return the value of list_field_entity.list_entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getList_entity_id() {
        return list_entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.list_entity_id
     *
     * @param list_entity_id the value for list_field_entity.list_entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setList_entity_id(Integer list_entity_id) {
        this.list_entity_id = list_entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.min_value
     *
     * @return the value of list_field_entity.min_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getMin_value() {
        return min_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.min_value
     *
     * @param min_value the value for list_field_entity.min_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setMin_value(Integer min_value) {
        this.min_value = min_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.max_value
     *
     * @return the value of list_field_entity.max_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getMax_value() {
        return max_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.max_value
     *
     * @param max_value the value for list_field_entity.max_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setMax_value(Integer max_value) {
        this.max_value = max_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.min_str_value
     *
     * @return the value of list_field_entity.min_str_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getMin_str_value() {
        return min_str_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.min_str_value
     *
     * @param min_str_value the value for list_field_entity.min_str_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setMin_str_value(String min_str_value) {
        this.min_str_value = min_str_value == null ? null : min_str_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.max_str_value
     *
     * @return the value of list_field_entity.max_str_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getMax_str_value() {
        return max_str_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.max_str_value
     *
     * @param max_str_value the value for list_field_entity.max_str_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setMax_str_value(String max_str_value) {
        this.max_str_value = max_str_value == null ? null : max_str_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.min_date_value
     *
     * @return the value of list_field_entity.min_date_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getMin_date_value() {
        return min_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.min_date_value
     *
     * @param min_date_value the value for list_field_entity.min_date_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setMin_date_value(Date min_date_value) {
        this.min_date_value = min_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.max_date_value
     *
     * @return the value of list_field_entity.max_date_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getMax_date_value() {
        return max_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.max_date_value
     *
     * @param max_date_value the value for list_field_entity.max_date_value
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setMax_date_value(Date max_date_value) {
        this.max_date_value = max_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_field_entity.OPTLOCK
     *
     * @return the value of list_field_entity.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_field_entity.OPTLOCK
     *
     * @param OPTLOCK the value for list_field_entity.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}