package db.billingdb.model;

import java.util.Date;

public class MediationRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediation_record.id_key
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private String id_key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediation_record.start_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date start_datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediation_record.mediation_process_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer mediation_process_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediation_record.status_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer status_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediation_record.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediation_record.id_key
     *
     * @return the value of mediation_record.id_key
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getId_key() {
        return id_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediation_record.id_key
     *
     * @param id_key the value for mediation_record.id_key
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId_key(String id_key) {
        this.id_key = id_key == null ? null : id_key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediation_record.start_datetime
     *
     * @return the value of mediation_record.start_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getStart_datetime() {
        return start_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediation_record.start_datetime
     *
     * @param start_datetime the value for mediation_record.start_datetime
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setStart_datetime(Date start_datetime) {
        this.start_datetime = start_datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediation_record.mediation_process_id
     *
     * @return the value of mediation_record.mediation_process_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getMediation_process_id() {
        return mediation_process_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediation_record.mediation_process_id
     *
     * @param mediation_process_id the value for mediation_record.mediation_process_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setMediation_process_id(Integer mediation_process_id) {
        this.mediation_process_id = mediation_process_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediation_record.status_id
     *
     * @return the value of mediation_record.status_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getStatus_id() {
        return status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediation_record.status_id
     *
     * @param status_id the value for mediation_record.status_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setStatus_id(Integer status_id) {
        this.status_id = status_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediation_record.OPTLOCK
     *
     * @return the value of mediation_record.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediation_record.OPTLOCK
     *
     * @param OPTLOCK the value for mediation_record.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}