package db.billingdb.model;

import java.util.Date;

public class PartnerPayout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.starting_date
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date starting_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.ending_date
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Date ending_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.payments_amount
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Double payments_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.refunds_amount
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Double refunds_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.balance_left
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Double balance_left;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.payment_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer payment_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.partner_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer partner_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_payout.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.id
     *
     * @return the value of partner_payout.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.id
     *
     * @param id the value for partner_payout.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.starting_date
     *
     * @return the value of partner_payout.starting_date
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getStarting_date() {
        return starting_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.starting_date
     *
     * @param starting_date the value for partner_payout.starting_date
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setStarting_date(Date starting_date) {
        this.starting_date = starting_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.ending_date
     *
     * @return the value of partner_payout.ending_date
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Date getEnding_date() {
        return ending_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.ending_date
     *
     * @param ending_date the value for partner_payout.ending_date
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEnding_date(Date ending_date) {
        this.ending_date = ending_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.payments_amount
     *
     * @return the value of partner_payout.payments_amount
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Double getPayments_amount() {
        return payments_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.payments_amount
     *
     * @param payments_amount the value for partner_payout.payments_amount
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setPayments_amount(Double payments_amount) {
        this.payments_amount = payments_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.refunds_amount
     *
     * @return the value of partner_payout.refunds_amount
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Double getRefunds_amount() {
        return refunds_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.refunds_amount
     *
     * @param refunds_amount the value for partner_payout.refunds_amount
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setRefunds_amount(Double refunds_amount) {
        this.refunds_amount = refunds_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.balance_left
     *
     * @return the value of partner_payout.balance_left
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Double getBalance_left() {
        return balance_left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.balance_left
     *
     * @param balance_left the value for partner_payout.balance_left
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setBalance_left(Double balance_left) {
        this.balance_left = balance_left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.payment_id
     *
     * @return the value of partner_payout.payment_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getPayment_id() {
        return payment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.payment_id
     *
     * @param payment_id the value for partner_payout.payment_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setPayment_id(Integer payment_id) {
        this.payment_id = payment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.partner_id
     *
     * @return the value of partner_payout.partner_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getPartner_id() {
        return partner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.partner_id
     *
     * @param partner_id the value for partner_payout.partner_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setPartner_id(Integer partner_id) {
        this.partner_id = partner_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_payout.OPTLOCK
     *
     * @return the value of partner_payout.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_payout.OPTLOCK
     *
     * @param OPTLOCK the value for partner_payout.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}