package db.billingdb.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PaymentAuthorizationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public PaymentAuthorizationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPayment_idIsNull() {
            addCriterion("payment_id is null");
            return (Criteria) this;
        }

        public Criteria andPayment_idIsNotNull() {
            addCriterion("payment_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayment_idEqualTo(Integer value) {
            addCriterion("payment_id =", value, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idNotEqualTo(Integer value) {
            addCriterion("payment_id <>", value, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idGreaterThan(Integer value) {
            addCriterion("payment_id >", value, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("payment_id >=", value, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idLessThan(Integer value) {
            addCriterion("payment_id <", value, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idLessThanOrEqualTo(Integer value) {
            addCriterion("payment_id <=", value, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idIn(List<Integer> values) {
            addCriterion("payment_id in", values, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idNotIn(List<Integer> values) {
            addCriterion("payment_id not in", values, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idBetween(Integer value1, Integer value2) {
            addCriterion("payment_id between", value1, value2, "payment_id");
            return (Criteria) this;
        }

        public Criteria andPayment_idNotBetween(Integer value1, Integer value2) {
            addCriterion("payment_id not between", value1, value2, "payment_id");
            return (Criteria) this;
        }

        public Criteria andProcessorIsNull() {
            addCriterion("processor is null");
            return (Criteria) this;
        }

        public Criteria andProcessorIsNotNull() {
            addCriterion("processor is not null");
            return (Criteria) this;
        }

        public Criteria andProcessorEqualTo(String value) {
            addCriterion("processor =", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotEqualTo(String value) {
            addCriterion("processor <>", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorGreaterThan(String value) {
            addCriterion("processor >", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorGreaterThanOrEqualTo(String value) {
            addCriterion("processor >=", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorLessThan(String value) {
            addCriterion("processor <", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorLessThanOrEqualTo(String value) {
            addCriterion("processor <=", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorLike(String value) {
            addCriterion("processor like", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotLike(String value) {
            addCriterion("processor not like", value, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorIn(List<String> values) {
            addCriterion("processor in", values, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotIn(List<String> values) {
            addCriterion("processor not in", values, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorBetween(String value1, String value2) {
            addCriterion("processor between", value1, value2, "processor");
            return (Criteria) this;
        }

        public Criteria andProcessorNotBetween(String value1, String value2) {
            addCriterion("processor not between", value1, value2, "processor");
            return (Criteria) this;
        }

        public Criteria andCode1IsNull() {
            addCriterion("code1 is null");
            return (Criteria) this;
        }

        public Criteria andCode1IsNotNull() {
            addCriterion("code1 is not null");
            return (Criteria) this;
        }

        public Criteria andCode1EqualTo(String value) {
            addCriterion("code1 =", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1NotEqualTo(String value) {
            addCriterion("code1 <>", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1GreaterThan(String value) {
            addCriterion("code1 >", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1GreaterThanOrEqualTo(String value) {
            addCriterion("code1 >=", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1LessThan(String value) {
            addCriterion("code1 <", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1LessThanOrEqualTo(String value) {
            addCriterion("code1 <=", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1Like(String value) {
            addCriterion("code1 like", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1NotLike(String value) {
            addCriterion("code1 not like", value, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1In(List<String> values) {
            addCriterion("code1 in", values, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1NotIn(List<String> values) {
            addCriterion("code1 not in", values, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1Between(String value1, String value2) {
            addCriterion("code1 between", value1, value2, "code1");
            return (Criteria) this;
        }

        public Criteria andCode1NotBetween(String value1, String value2) {
            addCriterion("code1 not between", value1, value2, "code1");
            return (Criteria) this;
        }

        public Criteria andCode2IsNull() {
            addCriterion("code2 is null");
            return (Criteria) this;
        }

        public Criteria andCode2IsNotNull() {
            addCriterion("code2 is not null");
            return (Criteria) this;
        }

        public Criteria andCode2EqualTo(String value) {
            addCriterion("code2 =", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2NotEqualTo(String value) {
            addCriterion("code2 <>", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2GreaterThan(String value) {
            addCriterion("code2 >", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2GreaterThanOrEqualTo(String value) {
            addCriterion("code2 >=", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2LessThan(String value) {
            addCriterion("code2 <", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2LessThanOrEqualTo(String value) {
            addCriterion("code2 <=", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2Like(String value) {
            addCriterion("code2 like", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2NotLike(String value) {
            addCriterion("code2 not like", value, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2In(List<String> values) {
            addCriterion("code2 in", values, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2NotIn(List<String> values) {
            addCriterion("code2 not in", values, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2Between(String value1, String value2) {
            addCriterion("code2 between", value1, value2, "code2");
            return (Criteria) this;
        }

        public Criteria andCode2NotBetween(String value1, String value2) {
            addCriterion("code2 not between", value1, value2, "code2");
            return (Criteria) this;
        }

        public Criteria andCode3IsNull() {
            addCriterion("code3 is null");
            return (Criteria) this;
        }

        public Criteria andCode3IsNotNull() {
            addCriterion("code3 is not null");
            return (Criteria) this;
        }

        public Criteria andCode3EqualTo(String value) {
            addCriterion("code3 =", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3NotEqualTo(String value) {
            addCriterion("code3 <>", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3GreaterThan(String value) {
            addCriterion("code3 >", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3GreaterThanOrEqualTo(String value) {
            addCriterion("code3 >=", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3LessThan(String value) {
            addCriterion("code3 <", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3LessThanOrEqualTo(String value) {
            addCriterion("code3 <=", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3Like(String value) {
            addCriterion("code3 like", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3NotLike(String value) {
            addCriterion("code3 not like", value, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3In(List<String> values) {
            addCriterion("code3 in", values, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3NotIn(List<String> values) {
            addCriterion("code3 not in", values, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3Between(String value1, String value2) {
            addCriterion("code3 between", value1, value2, "code3");
            return (Criteria) this;
        }

        public Criteria andCode3NotBetween(String value1, String value2) {
            addCriterion("code3 not between", value1, value2, "code3");
            return (Criteria) this;
        }

        public Criteria andApproval_codeIsNull() {
            addCriterion("approval_code is null");
            return (Criteria) this;
        }

        public Criteria andApproval_codeIsNotNull() {
            addCriterion("approval_code is not null");
            return (Criteria) this;
        }

        public Criteria andApproval_codeEqualTo(String value) {
            addCriterion("approval_code =", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeNotEqualTo(String value) {
            addCriterion("approval_code <>", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeGreaterThan(String value) {
            addCriterion("approval_code >", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeGreaterThanOrEqualTo(String value) {
            addCriterion("approval_code >=", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeLessThan(String value) {
            addCriterion("approval_code <", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeLessThanOrEqualTo(String value) {
            addCriterion("approval_code <=", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeLike(String value) {
            addCriterion("approval_code like", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeNotLike(String value) {
            addCriterion("approval_code not like", value, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeIn(List<String> values) {
            addCriterion("approval_code in", values, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeNotIn(List<String> values) {
            addCriterion("approval_code not in", values, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeBetween(String value1, String value2) {
            addCriterion("approval_code between", value1, value2, "approval_code");
            return (Criteria) this;
        }

        public Criteria andApproval_codeNotBetween(String value1, String value2) {
            addCriterion("approval_code not between", value1, value2, "approval_code");
            return (Criteria) this;
        }

        public Criteria andAvsIsNull() {
            addCriterion("avs is null");
            return (Criteria) this;
        }

        public Criteria andAvsIsNotNull() {
            addCriterion("avs is not null");
            return (Criteria) this;
        }

        public Criteria andAvsEqualTo(String value) {
            addCriterion("avs =", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsNotEqualTo(String value) {
            addCriterion("avs <>", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsGreaterThan(String value) {
            addCriterion("avs >", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsGreaterThanOrEqualTo(String value) {
            addCriterion("avs >=", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsLessThan(String value) {
            addCriterion("avs <", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsLessThanOrEqualTo(String value) {
            addCriterion("avs <=", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsLike(String value) {
            addCriterion("avs like", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsNotLike(String value) {
            addCriterion("avs not like", value, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsIn(List<String> values) {
            addCriterion("avs in", values, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsNotIn(List<String> values) {
            addCriterion("avs not in", values, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsBetween(String value1, String value2) {
            addCriterion("avs between", value1, value2, "avs");
            return (Criteria) this;
        }

        public Criteria andAvsNotBetween(String value1, String value2) {
            addCriterion("avs not between", value1, value2, "avs");
            return (Criteria) this;
        }

        public Criteria andTransaction_idIsNull() {
            addCriterion("transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andTransaction_idIsNotNull() {
            addCriterion("transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransaction_idEqualTo(String value) {
            addCriterion("transaction_id =", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotEqualTo(String value) {
            addCriterion("transaction_id <>", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idGreaterThan(String value) {
            addCriterion("transaction_id >", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_id >=", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idLessThan(String value) {
            addCriterion("transaction_id <", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idLessThanOrEqualTo(String value) {
            addCriterion("transaction_id <=", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idLike(String value) {
            addCriterion("transaction_id like", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotLike(String value) {
            addCriterion("transaction_id not like", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idIn(List<String> values) {
            addCriterion("transaction_id in", values, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotIn(List<String> values) {
            addCriterion("transaction_id not in", values, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idBetween(String value1, String value2) {
            addCriterion("transaction_id between", value1, value2, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotBetween(String value1, String value2) {
            addCriterion("transaction_id not between", value1, value2, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andMd5IsNull() {
            addCriterion("md5 is null");
            return (Criteria) this;
        }

        public Criteria andMd5IsNotNull() {
            addCriterion("md5 is not null");
            return (Criteria) this;
        }

        public Criteria andMd5EqualTo(String value) {
            addCriterion("md5 =", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotEqualTo(String value) {
            addCriterion("md5 <>", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5GreaterThan(String value) {
            addCriterion("md5 >", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5GreaterThanOrEqualTo(String value) {
            addCriterion("md5 >=", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5LessThan(String value) {
            addCriterion("md5 <", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5LessThanOrEqualTo(String value) {
            addCriterion("md5 <=", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5Like(String value) {
            addCriterion("md5 like", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotLike(String value) {
            addCriterion("md5 not like", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5In(List<String> values) {
            addCriterion("md5 in", values, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotIn(List<String> values) {
            addCriterion("md5 not in", values, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5Between(String value1, String value2) {
            addCriterion("md5 between", value1, value2, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotBetween(String value1, String value2) {
            addCriterion("md5 not between", value1, value2, "md5");
            return (Criteria) this;
        }

        public Criteria andCard_codeIsNull() {
            addCriterion("card_code is null");
            return (Criteria) this;
        }

        public Criteria andCard_codeIsNotNull() {
            addCriterion("card_code is not null");
            return (Criteria) this;
        }

        public Criteria andCard_codeEqualTo(String value) {
            addCriterion("card_code =", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeNotEqualTo(String value) {
            addCriterion("card_code <>", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeGreaterThan(String value) {
            addCriterion("card_code >", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeGreaterThanOrEqualTo(String value) {
            addCriterion("card_code >=", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeLessThan(String value) {
            addCriterion("card_code <", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeLessThanOrEqualTo(String value) {
            addCriterion("card_code <=", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeLike(String value) {
            addCriterion("card_code like", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeNotLike(String value) {
            addCriterion("card_code not like", value, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeIn(List<String> values) {
            addCriterion("card_code in", values, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeNotIn(List<String> values) {
            addCriterion("card_code not in", values, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeBetween(String value1, String value2) {
            addCriterion("card_code between", value1, value2, "card_code");
            return (Criteria) this;
        }

        public Criteria andCard_codeNotBetween(String value1, String value2) {
            addCriterion("card_code not between", value1, value2, "card_code");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andResponse_messageIsNull() {
            addCriterion("response_message is null");
            return (Criteria) this;
        }

        public Criteria andResponse_messageIsNotNull() {
            addCriterion("response_message is not null");
            return (Criteria) this;
        }

        public Criteria andResponse_messageEqualTo(String value) {
            addCriterion("response_message =", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageNotEqualTo(String value) {
            addCriterion("response_message <>", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageGreaterThan(String value) {
            addCriterion("response_message >", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageGreaterThanOrEqualTo(String value) {
            addCriterion("response_message >=", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageLessThan(String value) {
            addCriterion("response_message <", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageLessThanOrEqualTo(String value) {
            addCriterion("response_message <=", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageLike(String value) {
            addCriterion("response_message like", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageNotLike(String value) {
            addCriterion("response_message not like", value, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageIn(List<String> values) {
            addCriterion("response_message in", values, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageNotIn(List<String> values) {
            addCriterion("response_message not in", values, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageBetween(String value1, String value2) {
            addCriterion("response_message between", value1, value2, "response_message");
            return (Criteria) this;
        }

        public Criteria andResponse_messageNotBetween(String value1, String value2) {
            addCriterion("response_message not between", value1, value2, "response_message");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIsNull() {
            addCriterion("OPTLOCK is null");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIsNotNull() {
            addCriterion("OPTLOCK is not null");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKEqualTo(Integer value) {
            addCriterion("OPTLOCK =", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotEqualTo(Integer value) {
            addCriterion("OPTLOCK <>", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKGreaterThan(Integer value) {
            addCriterion("OPTLOCK >", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPTLOCK >=", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKLessThan(Integer value) {
            addCriterion("OPTLOCK <", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKLessThanOrEqualTo(Integer value) {
            addCriterion("OPTLOCK <=", value, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKIn(List<Integer> values) {
            addCriterion("OPTLOCK in", values, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotIn(List<Integer> values) {
            addCriterion("OPTLOCK not in", values, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKBetween(Integer value1, Integer value2) {
            addCriterion("OPTLOCK between", value1, value2, "OPTLOCK");
            return (Criteria) this;
        }

        public Criteria andOPTLOCKNotBetween(Integer value1, Integer value2) {
            addCriterion("OPTLOCK not between", value1, value2, "OPTLOCK");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table payment_authorization
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 21:28:38 IST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}