package db.billingdb.model;

public class PermissionType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_type.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_type.description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_type.id
     *
     * @return the value of permission_type.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_type.id
     *
     * @param id the value for permission_type.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_type.description
     *
     * @return the value of permission_type.description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_type.description
     *
     * @param description the value for permission_type.description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}