package db.billingdb.model;

public class PluggableTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluggable_task.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluggable_task.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluggable_task.type_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluggable_task.processing_order
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer processing_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pluggable_task.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluggable_task.id
     *
     * @return the value of pluggable_task.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluggable_task.id
     *
     * @param id the value for pluggable_task.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluggable_task.entity_id
     *
     * @return the value of pluggable_task.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluggable_task.entity_id
     *
     * @param entity_id the value for pluggable_task.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluggable_task.type_id
     *
     * @return the value of pluggable_task.type_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluggable_task.type_id
     *
     * @param type_id the value for pluggable_task.type_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluggable_task.processing_order
     *
     * @return the value of pluggable_task.processing_order
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getProcessing_order() {
        return processing_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluggable_task.processing_order
     *
     * @param processing_order the value for pluggable_task.processing_order
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setProcessing_order(Integer processing_order) {
        this.processing_order = processing_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pluggable_task.OPTLOCK
     *
     * @return the value of pluggable_task.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pluggable_task.OPTLOCK
     *
     * @param OPTLOCK the value for pluggable_task.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}