package db.billingdb.model;

public class ProcessRunTotal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_run_total.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_run_total.process_run_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer process_run_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_run_total.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer currency_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_run_total.total_invoiced
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Double total_invoiced;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_run_total.total_paid
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Double total_paid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_run_total.total_not_paid
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Double total_not_paid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_run_total.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer OPTLOCK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_run_total.id
     *
     * @return the value of process_run_total.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_run_total.id
     *
     * @param id the value for process_run_total.id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_run_total.process_run_id
     *
     * @return the value of process_run_total.process_run_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getProcess_run_id() {
        return process_run_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_run_total.process_run_id
     *
     * @param process_run_id the value for process_run_total.process_run_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setProcess_run_id(Integer process_run_id) {
        this.process_run_id = process_run_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_run_total.currency_id
     *
     * @return the value of process_run_total.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getCurrency_id() {
        return currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_run_total.currency_id
     *
     * @param currency_id the value for process_run_total.currency_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCurrency_id(Integer currency_id) {
        this.currency_id = currency_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_run_total.total_invoiced
     *
     * @return the value of process_run_total.total_invoiced
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Double getTotal_invoiced() {
        return total_invoiced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_run_total.total_invoiced
     *
     * @param total_invoiced the value for process_run_total.total_invoiced
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setTotal_invoiced(Double total_invoiced) {
        this.total_invoiced = total_invoiced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_run_total.total_paid
     *
     * @return the value of process_run_total.total_paid
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Double getTotal_paid() {
        return total_paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_run_total.total_paid
     *
     * @param total_paid the value for process_run_total.total_paid
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setTotal_paid(Double total_paid) {
        this.total_paid = total_paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_run_total.total_not_paid
     *
     * @return the value of process_run_total.total_not_paid
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Double getTotal_not_paid() {
        return total_not_paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_run_total.total_not_paid
     *
     * @param total_not_paid the value for process_run_total.total_not_paid
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setTotal_not_paid(Double total_not_paid) {
        this.total_not_paid = total_not_paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_run_total.OPTLOCK
     *
     * @return the value of process_run_total.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getOPTLOCK() {
        return OPTLOCK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_run_total.OPTLOCK
     *
     * @param OPTLOCK the value for process_run_total.OPTLOCK
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setOPTLOCK(Integer OPTLOCK) {
        this.OPTLOCK = OPTLOCK;
    }
}