package db.billingdb.model;

public class ReportEntityMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_entity_map.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer entity_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_entity_map.report_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer report_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_entity_map.entity_id
     *
     * @return the value of report_entity_map.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getEntity_id() {
        return entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_entity_map.entity_id
     *
     * @param entity_id the value for report_entity_map.entity_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setEntity_id(Integer entity_id) {
        this.entity_id = entity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_entity_map.report_id
     *
     * @return the value of report_entity_map.report_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getReport_id() {
        return report_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_entity_map.report_id
     *
     * @param report_id the value for report_entity_map.report_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setReport_id(Integer report_id) {
        this.report_id = report_id;
    }
}