package db.billingdb.model;

public class UserCreditCardMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credit_card_map.user_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_credit_card_map.credit_card_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    private Integer credit_card_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credit_card_map.user_id
     *
     * @return the value of user_credit_card_map.user_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credit_card_map.user_id
     *
     * @param user_id the value for user_credit_card_map.user_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_credit_card_map.credit_card_id
     *
     * @return the value of user_credit_card_map.credit_card_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public Integer getCredit_card_id() {
        return credit_card_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_credit_card_map.credit_card_id
     *
     * @param credit_card_id the value for user_credit_card_map.credit_card_id
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    public void setCredit_card_id(Integer credit_card_id) {
        this.credit_card_id = credit_card_id;
    }
}