package db.billingdb.dao;

import db.billingdb.model.ContactMap;
import db.billingdb.model.ContactMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContactMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(ContactMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(ContactMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(ContactMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(ContactMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<ContactMap> selectByExample(ContactMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    ContactMap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") ContactMap record, @Param("example") ContactMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") ContactMap record, @Param("example") ContactMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(ContactMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(ContactMap record);
}