package db.billingdb.dao;

import db.billingdb.model.EntityPaymentMethodMap;
import db.billingdb.model.EntityPaymentMethodMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntityPaymentMethodMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_payment_method_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(EntityPaymentMethodMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_payment_method_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(EntityPaymentMethodMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_payment_method_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(EntityPaymentMethodMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_payment_method_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(EntityPaymentMethodMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_payment_method_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<EntityPaymentMethodMap> selectByExample(EntityPaymentMethodMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_payment_method_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") EntityPaymentMethodMap record, @Param("example") EntityPaymentMethodMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_payment_method_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") EntityPaymentMethodMap record, @Param("example") EntityPaymentMethodMapExample example);
}