package db.billingdb.dao;

import db.billingdb.model.EventLog;
import db.billingdb.model.EventLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(EventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(EventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<EventLog> selectByExample(EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    EventLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") EventLog record, @Param("example") EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") EventLog record, @Param("example") EventLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(EventLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_log
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(EventLog record);
}