package db.billingdb.dao;

import db.billingdb.model.InternationalDescription;
import db.billingdb.model.InternationalDescriptionExample;
import db.billingdb.model.InternationalDescriptionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InternationalDescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(InternationalDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(InternationalDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(InternationalDescriptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(InternationalDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(InternationalDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<InternationalDescription> selectByExample(InternationalDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    InternationalDescription selectByPrimaryKey(InternationalDescriptionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") InternationalDescription record, @Param("example") InternationalDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") InternationalDescription record, @Param("example") InternationalDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(InternationalDescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table international_description
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(InternationalDescription record);
}