package db.billingdb.dao;

import java.util.List;

import db.billingdb.model.ListExample;
import org.apache.ibatis.annotations.Param;

public interface ListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(ListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(ListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(db.billingdb.model.List record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(db.billingdb.model.List record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<db.billingdb.model.List> selectByExample(ListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    db.billingdb.model.List selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") db.billingdb.model.List record, @Param("example") ListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") db.billingdb.model.List record, @Param("example") ListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(db.billingdb.model.List record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(db.billingdb.model.List record);
}