package db.billingdb.dao;

import db.billingdb.model.ListFieldEntity;
import db.billingdb.model.ListFieldEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ListFieldEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(ListFieldEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(ListFieldEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(ListFieldEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(ListFieldEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<ListFieldEntity> selectByExample(ListFieldEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    ListFieldEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") ListFieldEntity record, @Param("example") ListFieldEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") ListFieldEntity record, @Param("example") ListFieldEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(ListFieldEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_field_entity
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(ListFieldEntity record);
}