package db.billingdb.dao;

import db.billingdb.model.MenuOption;
import db.billingdb.model.MenuOptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(MenuOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(MenuOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(MenuOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(MenuOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<MenuOption> selectByExample(MenuOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    MenuOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") MenuOption record, @Param("example") MenuOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") MenuOption record, @Param("example") MenuOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(MenuOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_option
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(MenuOption record);
}