package db.billingdb.dao;

import db.billingdb.model.NotificationMessageSection;
import db.billingdb.model.NotificationMessageSectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotificationMessageSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(NotificationMessageSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(NotificationMessageSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(NotificationMessageSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(NotificationMessageSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<NotificationMessageSection> selectByExample(NotificationMessageSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    NotificationMessageSection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") NotificationMessageSection record, @Param("example") NotificationMessageSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") NotificationMessageSection record, @Param("example") NotificationMessageSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(NotificationMessageSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_message_section
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(NotificationMessageSection record);
}