package db.billingdb.dao;

import db.billingdb.model.PaperInvoiceBatch;
import db.billingdb.model.PaperInvoiceBatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperInvoiceBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(PaperInvoiceBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(PaperInvoiceBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(PaperInvoiceBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(PaperInvoiceBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<PaperInvoiceBatch> selectByExample(PaperInvoiceBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    PaperInvoiceBatch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") PaperInvoiceBatch record, @Param("example") PaperInvoiceBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") PaperInvoiceBatch record, @Param("example") PaperInvoiceBatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(PaperInvoiceBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_invoice_batch
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(PaperInvoiceBatch record);
}