package db.billingdb.dao;

import db.billingdb.model.PartnerRange;
import db.billingdb.model.PartnerRangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerRangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(PartnerRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(PartnerRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(PartnerRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(PartnerRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<PartnerRange> selectByExample(PartnerRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    PartnerRange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") PartnerRange record, @Param("example") PartnerRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") PartnerRange record, @Param("example") PartnerRangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(PartnerRange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_range
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(PartnerRange record);
}