package db.billingdb.dao;

import db.billingdb.model.PaymentAuthorization;
import db.billingdb.model.PaymentAuthorizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(PaymentAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(PaymentAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(PaymentAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(PaymentAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<PaymentAuthorization> selectByExample(PaymentAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    PaymentAuthorization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") PaymentAuthorization record, @Param("example") PaymentAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") PaymentAuthorization record, @Param("example") PaymentAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(PaymentAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_authorization
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(PaymentAuthorization record);
}