package db.billingdb.dao;

import db.billingdb.model.PaymentInvoice;
import db.billingdb.model.PaymentInvoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(PaymentInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(PaymentInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(PaymentInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(PaymentInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<PaymentInvoice> selectByExample(PaymentInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    PaymentInvoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") PaymentInvoice record, @Param("example") PaymentInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") PaymentInvoice record, @Param("example") PaymentInvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(PaymentInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_invoice
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(PaymentInvoice record);
}