package db.billingdb.dao;

import db.billingdb.model.PeriodUnit;
import db.billingdb.model.PeriodUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PeriodUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(PeriodUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(PeriodUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(PeriodUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(PeriodUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<PeriodUnit> selectByExample(PeriodUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") PeriodUnit record, @Param("example") PeriodUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table period_unit
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") PeriodUnit record, @Param("example") PeriodUnitExample example);
}