package db.billingdb.dao;

import db.billingdb.model.PermissionRoleMap;
import db.billingdb.model.PermissionRoleMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionRoleMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(PermissionRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(PermissionRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(PermissionRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(PermissionRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<PermissionRoleMap> selectByExample(PermissionRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") PermissionRoleMap record, @Param("example") PermissionRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") PermissionRoleMap record, @Param("example") PermissionRoleMapExample example);
}