package db.billingdb.dao;

import db.billingdb.model.PermissionUser;
import db.billingdb.model.PermissionUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(PermissionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(PermissionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(PermissionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(PermissionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<PermissionUser> selectByExample(PermissionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    PermissionUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") PermissionUser record, @Param("example") PermissionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") PermissionUser record, @Param("example") PermissionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(PermissionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(PermissionUser record);
}