package db.billingdb.dao;

import db.billingdb.model.ProcessRunTotal;
import db.billingdb.model.ProcessRunTotalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessRunTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(ProcessRunTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(ProcessRunTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(ProcessRunTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(ProcessRunTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<ProcessRunTotal> selectByExample(ProcessRunTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    ProcessRunTotal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") ProcessRunTotal record, @Param("example") ProcessRunTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") ProcessRunTotal record, @Param("example") ProcessRunTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(ProcessRunTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_run_total
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(ProcessRunTotal record);
}