package db.billingdb.dao;

import db.billingdb.model.ReportType;
import db.billingdb.model.ReportTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(ReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(ReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<ReportType> selectByExample(ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    ReportType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") ReportType record, @Param("example") ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") ReportType record, @Param("example") ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(ReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_type
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(ReportType record);
}