package db.billingdb.dao;

import db.billingdb.model.ReportUser;
import db.billingdb.model.ReportUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(ReportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(ReportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(ReportUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(ReportUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<ReportUser> selectByExample(ReportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    ReportUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") ReportUser record, @Param("example") ReportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") ReportUser record, @Param("example") ReportUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKeySelective(ReportUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_user
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByPrimaryKey(ReportUser record);
}