package db.billingdb.dao;

import db.billingdb.model.UserRoleMap;
import db.billingdb.model.UserRoleMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(UserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(UserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(UserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(UserRoleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<UserRoleMap> selectByExample(UserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") UserRoleMap record, @Param("example") UserRoleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") UserRoleMap record, @Param("example") UserRoleMapExample example);
}