package db.billingdb.dao;

import db.billingdb.model.UserCreditCardMap;
import db.billingdb.model.UserCreditCardMapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCreditCardMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_card_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int countByExample(UserCreditCardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_card_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int deleteByExample(UserCreditCardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_card_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insert(UserCreditCardMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_card_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int insertSelective(UserCreditCardMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_card_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    List<UserCreditCardMap> selectByExample(UserCreditCardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_card_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExampleSelective(@Param("record") UserCreditCardMap record, @Param("example") UserCreditCardMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_card_map
     *
     * @mbggenerated Tue Feb 18 21:28:38 IST 2014
     */
    int updateByExample(@Param("record") UserCreditCardMap record, @Param("example") UserCreditCardMapExample example);
}